#!/usr/bin/env python3
"""SQL to load school-posted 2026-27 rosters straight into Supabase (teams + players) for programs the
Sheet hasn't synced yet — the owner runs it in the SQL editor instead of the Sheet's three-step flow.

    python3 scripts/build_roster_insert_sql.py "Florida A&M" Queens ...   → scripts/roster_insert_<date>.sql

Reads scripts/data/roster_diff_2027.json (classification + ESPN ids from build_roster_diff.py). Idempotent:
a team or (name, team) player that already exists is left alone. An ESPN id already on ANOTHER current
roster is left off (null) and listed in the header — the old school's row is the one to clean up first.
"""
import json, sys, datetime, urllib.request, re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SB = "https://izlqhnxowdhtdofkwrho.supabase.co/rest/v1"
CLS_ORDER = {"Gr.": 0, "Sr.": 1, "R-Sr.": 1, "Jr.": 2, "R-Jr.": 2, "So.": 3, "R-So.": 3, "Fr.": 4, "R-Fr.": 4}


def anon():
    return re.search(r"sb_publishable_[A-Za-z0-9_-]+", (ROOT / "player.html").read_text()).group(0)


def taken_espn():
    k = anon(); h = {"apikey": k, "Authorization": "Bearer " + k}; out, off = {}, 0
    while True:
        rows = json.load(urllib.request.urlopen(urllib.request.Request(
            f"{SB}/players?select=id,espn_id,name,team&espn_id=not.is.null&order=id.asc&limit=1000&offset={off}", headers=h)))
        for r in rows: out[str(r["espn_id"])] = r
        if len(rows) < 1000: return out
        off += 1000


def q(v):
    if v is None or v == "": return "null"
    if isinstance(v, bool): return "true" if v else "false"
    if isinstance(v, (int, float)): return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    want = sys.argv[1:]
    diff = {d["team"]: d for d in json.load(open(ROOT / "scripts/data/roster_diff_2027.json"))}
    sites = json.load(open(ROOT / "scripts/data/school_sites.json"))
    taken = taken_espn()
    out, notes = [], []
    for team in want:
        d = diff.get(team)
        if not d or not d.get("players") or d.get("season") == "2025-26" or d.get("error"):
            notes.append(f"-- SKIPPED {team}: no posted 2026-27 roster in roster_diff_2027.json"); continue
        conf = d.get("conf") or (sites.get(team) or {}).get("conf")
        coach = d.get("coach") or (sites.get(team) or {}).get("coach")
        ps = d["players"]
        # depth: last season's minutes first (real rotation players), then class (seniors before freshmen)
        ps = sorted(ps, key=lambda p: (-(p.get("last_mpg") or 0), CLS_ORDER.get(p.get("sheet_yr") or "", 5), p["name"]))
        out.append(f"\n-- ── {team} ({conf}, {len(ps)} players{', coach ' + coach if coach else ''}) ──")
        out.append(f"insert into teams (name, conference, conf, head_coach, coach)\n"
                   f"select {q(team)}, {q(conf)}, {q(conf)}, {q(coach)}, {q(coach)}\n"
                   f"where not exists (select 1 from teams where name = {q(team)});")
        rows = []
        for i, p in enumerate(ps, 1):
            e = str(p["espn_id"]) if p.get("espn_id") else None
            if e and e in taken and taken[e]["team"] != team:
                notes.append(f"--   {team}: {p['name']} — ESPN id {e} is still on {taken[e]['team']}'s roster "
                             f"(players.id {taken[e]['id']}, \"{taken[e]['name']}\"); loaded without the id")
                e = None
            yr = p.get("sheet_yr") or None
            # players.hometown holds a transfer's PREVIOUS SCHOOL on this site (the roster "from" column), not a town
            frm = (p.get("sheet_from") or p.get("from_team")) if p.get("status") == "transfer" else None
            rows.append("  (" + ", ".join([q(p["name"]), q(team), q(p.get("sheet_pos")), q(yr), q(yr), q(p.get("ht")),
                q(frm), q(int(e) if e else None), q(i), q(i <= 5), q(p.get("status") != "returner"),
                q(bool(p.get("intl"))), "false"]) + ")")
        out.append("insert into players (name, team, position, class_year, yr, height, hometown,\n"
                   "  espn_id, depth_order, starter, is_addition, is_international, is_injured)\n"
                   "select v.name, v.team, v.position, v.class_year, v.yr, v.height, v.hometown::text,\n"
                   "  v.espn_id::bigint, v.depth_order, v.starter, v.is_addition, v.is_international, v.is_injured from (values\n" + ",\n".join(rows) + "\n) as v(name, team, position, class_year, yr, height,\n"
                   "  hometown, espn_id, depth_order, starter, is_addition, is_international, is_injured)\n"
                   "where not exists (select 1 from players p where p.name = v.name and p.team = v.team);")
    day = datetime.date.today().isoformat()
    head = [f"-- Load school-posted 2026-27 rosters for programs not yet on the site ({day}).",
            "-- Generated by scripts/build_roster_insert_sql.py from roster_diff_2027.json. Safe to re-run:",
            "-- existing teams and (name, team) players are left alone. Run in the Supabase SQL editor.",
            "-- Afterwards, in the owner console: 🔁 Rebuild projections, then ⚡ Republish projected ratings and 🏆 Republish awards."]
    if notes: head += ["--", "-- Notes:"] + notes
    path = ROOT / "scripts" / f"roster_insert_{day}.sql"
    path.write_text("\n".join(head) + "\n" + "\n".join(out) + "\n")
    print(f"wrote {path.relative_to(ROOT)}"); print("\n".join(notes) if notes else "no conflicts")


if __name__ == "__main__":
    main()
