-- Load school-posted 2026-27 rosters for programs not yet on the site (2026-10-06).
-- Generated by scripts/build_roster_insert_sql.py from roster_diff_2027.json. Safe to re-run:
-- existing teams and (name, team) players are left alone. Run in the Supabase SQL editor.
-- Afterwards, in the owner console: 🔁 Rebuild projections, then ⚡ Republish projected ratings and 🏆 Republish awards.

-- ── Florida A&M (SWAC, 15 players, coach Charlie Ward) ──
insert into teams (name, conference, conf, head_coach, coach)
select 'Florida A&M', 'SWAC', 'SWAC', 'Charlie Ward', 'Charlie Ward'
where not exists (select 1 from teams where name = 'Florida A&M');
insert into players (name, team, position, class_year, yr, height, hometown,
  espn_id, depth_order, starter, is_addition, is_international, is_injured)
select v.name, v.team, v.position, v.class_year, v.yr, v.height, v.hometown::text,
  v.espn_id::bigint, v.depth_order, v.starter, v.is_addition, v.is_international, v.is_injured from (values
  ('Jaquan Sanders', 'Florida A&M', 'SG', 'Gr.', 'Gr.', '6-4', null, 5105593, 1, true, false, false, false),
  ('Jaden Kempson', 'Florida A&M', 'SG', 'Sr.', 'Sr.', '6-3', 'UAlbany', 5313144, 2, true, true, false, false),
  ('Antonio Baker Jr.', 'Florida A&M', 'SG', 'Sr.', 'Sr.', '6-3', null, 5325879, 3, true, false, false, false),
  ('Ralph Martino Jr.', 'Florida A&M', 'SG', 'Jr.', 'Jr.', '6-7', 'Saint Francis', 5243388, 4, true, true, false, false),
  ('Tuscan Onuoha', 'Florida A&M', 'PF', 'Gr.', 'Gr.', '6-11', null, 5241426, 5, true, false, true, false),
  ('Assane Mbaye', 'Florida A&M', 'C', 'Jr.', 'Jr.', '7-3', 'Seton Hall', 5240537, 6, false, true, true, false),
  ('Chandler Davis', 'Florida A&M', 'SG', 'Jr.', 'Jr.', '6-6', null, null, 7, false, true, false, false),
  ('Daisean Williford', 'Florida A&M', 'SF', 'Jr.', 'Jr.', '6-7', null, null, 8, false, true, false, false),
  ('Mihailo Stijovic', 'Florida A&M', 'PF', 'Jr.', 'Jr.', '7-1', null, null, 9, false, true, true, false),
  ('Alex Montes', 'Florida A&M', 'SG', 'So.', 'So.', '6-5', null, null, 10, false, true, false, false),
  ('Ashton Williams', 'Florida A&M', 'SG', 'So.', 'So.', '6-3', null, null, 11, false, true, false, false),
  ('Ben Ndour', 'Florida A&M', 'PF', 'Fr.', 'Fr.', '6-9', null, null, 12, false, true, true, false),
  ('Jakub Lomicka', 'Florida A&M', 'PF', 'Fr.', 'Fr.', '6-11', null, null, 13, false, true, true, false),
  ('Jayden Joseph', 'Florida A&M', 'PG', 'Fr.', 'Fr.', '6-2', null, null, 14, false, true, false, false),
  ('Joel Mokweza', 'Florida A&M', 'C', 'Fr.', 'Fr.', '6-10', null, null, 15, false, true, true, false)
) as v(name, team, position, class_year, yr, height,
  hometown, espn_id, depth_order, starter, is_addition, is_international, is_injured)
where not exists (select 1 from players p where p.name = v.name and p.team = v.team);

-- ── Incarnate Word (Southland, 15 players, coach Shane Heirman) ──
insert into teams (name, conference, conf, head_coach, coach)
select 'Incarnate Word', 'Southland', 'Southland', 'Shane Heirman', 'Shane Heirman'
where not exists (select 1 from teams where name = 'Incarnate Word');
insert into players (name, team, position, class_year, yr, height, hometown,
  espn_id, depth_order, starter, is_addition, is_international, is_injured)
select v.name, v.team, v.position, v.class_year, v.yr, v.height, v.hometown::text,
  v.espn_id::bigint, v.depth_order, v.starter, v.is_addition, v.is_international, v.is_injured from (values
  ('Brandon McCreesh', 'Incarnate Word', 'SG', 'Sr.', 'Sr.', '6-3', 'Bucknell', 5176043, 1, true, true, false, false),
  ('Ismail Habib', 'Incarnate Word', 'PG', 'Sr.', 'Sr.', '6-0', 'Portland State', 4711838, 2, true, true, false, false),
  ('D''Arrae Goodwin', 'Incarnate Word', 'SF', 'So.', 'So.', '6-7', 'San Diego', 5313155, 3, true, true, true, false),
  ('Kaleb Spencer', 'Incarnate Word', 'PF', 'So.', 'So.', '6-9', 'William & Mary', 5312330, 4, true, true, false, false),
  ('Drew Barbee', 'Incarnate Word', 'SG', 'Jr.', 'Jr.', '6-5', null, 5176183, 5, true, false, false, false),
  ('DJ Cason', 'Incarnate Word', 'PG', 'Jr.', 'Jr.', '6-1', null, null, 6, false, true, false, false),
  ('David Emetu', 'Incarnate Word', 'SF', 'Jr.', 'Jr.', '6-8', null, null, 7, false, true, true, false),
  ('Godswill Erherine', 'Incarnate Word', 'PF', 'Jr.', 'Jr.', '6-9', null, null, 8, false, true, true, false),
  ('Jayden Thomas', 'Incarnate Word', 'SG', 'Jr.', 'Jr.', '6-5', null, null, 9, false, true, false, false),
  ('Mekhi Connor', 'Incarnate Word', 'PG', 'Jr.', 'Jr.', '6-1', null, null, 10, false, true, false, false),
  ('Christophe Pare', 'Incarnate Word', 'C', 'Fr.', 'Fr.', '7-0', null, null, 11, false, true, true, false),
  ('Krisnan Ioane', 'Incarnate Word', 'SF', 'Fr.', 'Fr.', '6-6', null, null, 12, false, true, true, false),
  ('Marc Harvey', 'Incarnate Word', 'SG', 'Fr.', 'Fr.', '6-3', null, null, 13, false, true, false, false),
  ('Tristan Collins', 'Incarnate Word', 'SF', 'Fr.', 'Fr.', '6-6', null, null, 14, false, true, false, false),
  ('Max Garcia-Plata', 'Incarnate Word', 'SG', 'R-Fr.', 'R-Fr.', '6-4', null, null, 15, false, true, true, false)
) as v(name, team, position, class_year, yr, height,
  hometown, espn_id, depth_order, starter, is_addition, is_international, is_injured)
where not exists (select 1 from players p where p.name = v.name and p.team = v.team);

-- ── Lindenwood (OVC, 15 players) ──
insert into teams (name, conference, conf, head_coach, coach)
select 'Lindenwood', 'OVC', 'OVC', null, null
where not exists (select 1 from teams where name = 'Lindenwood');
insert into players (name, team, position, class_year, yr, height, hometown,
  espn_id, depth_order, starter, is_addition, is_international, is_injured)
select v.name, v.team, v.position, v.class_year, v.yr, v.height, v.hometown::text,
  v.espn_id::bigint, v.depth_order, v.starter, v.is_addition, v.is_international, v.is_injured from (values
  ('Xavier Spencer', 'Lindenwood', 'PG', 'Sr.', 'Sr.', '6-1', 'UMass Lowell', 5313152, 1, true, true, true, false),
  ('Miles White', 'Lindenwood', 'SG', 'Sr.', 'Sr.', '6-3', 'Lipscomb', 5239794, 2, true, true, false, false),
  ('Matar Diop', 'Lindenwood', 'PF', 'Sr.', 'Sr.', '6-10', 'Stetson', 5174799, 3, true, true, true, false),
  ('Malek Archie', 'Lindenwood', 'PG', 'Jr.', 'Jr.', '6-2', 'Tarleton State', 5241437, 4, true, true, false, false),
  ('Makhan Diouf', 'Lindenwood', 'PF', 'Jr.', 'Jr.', '6-11', 'Fresno State', 5142617, 5, true, true, true, false),
  ('Marsai Mason', 'Lindenwood', 'SG', 'Jr.', 'Jr.', '6-6', null, null, 6, false, true, false, false),
  ('Shamiere Green', 'Lindenwood', 'SG', 'Jr.', 'Jr.', '6-4', null, null, 7, false, true, false, false),
  ('Dom Clay', 'Lindenwood', 'SG', 'So.', 'So.', '6-3', null, null, 8, false, true, false, false),
  ('Kellen Robinson', 'Lindenwood', 'SG', 'So.', 'So.', '6-3', null, null, 9, false, true, false, false),
  ('William Campbell', 'Lindenwood', 'SG', 'So.', 'So.', '6-4', null, null, 10, false, true, false, false),
  ('Derek Rollins', 'Lindenwood', 'SF', 'Fr.', 'Fr.', '6-5', null, null, 11, false, true, false, false),
  ('Marko Lukanoski', 'Lindenwood', 'C', 'Fr.', 'Fr.', '6-10', null, null, 12, false, true, true, false),
  ('Miles Elliott', 'Lindenwood', 'SG', 'Fr.', 'Fr.', '6-3', null, null, 13, false, true, false, false),
  ('Parker Seithel', 'Lindenwood', 'C', 'Fr.', 'Fr.', '6-10', null, null, 14, false, true, false, false),
  ('RJ Chastang', 'Lindenwood', 'SG', 'Fr.', 'Fr.', '6-4', null, null, 15, false, true, false, false)
) as v(name, team, position, class_year, yr, height,
  hometown, espn_id, depth_order, starter, is_addition, is_international, is_injured)
where not exists (select 1 from players p where p.name = v.name and p.team = v.team);

-- ── Prairie View A&M (SWAC, 14 players, coach Byron Smith) ──
insert into teams (name, conference, conf, head_coach, coach)
select 'Prairie View A&M', 'SWAC', 'SWAC', 'Byron Smith', 'Byron Smith'
where not exists (select 1 from teams where name = 'Prairie View A&M');
insert into players (name, team, position, class_year, yr, height, hometown,
  espn_id, depth_order, starter, is_addition, is_international, is_injured)
select v.name, v.team, v.position, v.class_year, v.yr, v.height, v.hometown::text,
  v.espn_id::bigint, v.depth_order, v.starter, v.is_addition, v.is_international, v.is_injured from (values
  ('Davian Williams', 'Prairie View A&M', 'PG', 'Jr.', 'Jr.', '5-10', 'Alcorn State', 5243188, 1, true, true, false, false),
  ('Michael Eley', 'Prairie View A&M', 'SG', 'Gr.', 'Gr.', '6-4', 'Hampton', 5107807, 2, true, true, false, false),
  ('Sebastian Tidor', 'Prairie View A&M', 'SG', 'Gr.', 'Gr.', '6-4', 'Portland State', 5241303, 3, true, true, false, false),
  ('Elijah Mitchell', 'Prairie View A&M', 'SG', 'Jr.', 'Jr.', '6-5', null, 5314805, 4, true, false, false, false),
  ('Jaylen Wharton', 'Prairie View A&M', 'PF', 'Gr.', 'Gr.', '6-9', 'Northern Illinois', 5240355, 5, true, true, false, false),
  ('Micah Bell', 'Prairie View A&M', 'SG', 'Jr.', 'Jr.', '6-4', 'Ball State', 5108054, 6, false, true, false, false),
  ('Anthony Gause', 'Prairie View A&M', 'PG', 'R-So.', 'R-So.', '6-2', 'Charleston Southern', 5240411, 7, false, true, false, false),
  ('Jackson Fazande', 'Prairie View A&M', 'SF', 'Jr.', 'Jr.', '6-5', 'UTSA', 5240408, 8, false, true, false, false),
  ('Eddie Page', 'Prairie View A&M', 'PF', 'Gr.', 'Gr.', '6-9', null, null, 9, false, true, false, false),
  ('Jaylen Lee', 'Prairie View A&M', 'SG', 'Gr.', 'Gr.', '6-6', null, null, 10, false, true, false, false),
  ('Bryant Aijero', 'Prairie View A&M', 'PF', 'Jr.', 'Jr.', '6-9', null, null, 11, false, true, false, false),
  ('Dashawn Ceaser', 'Prairie View A&M', 'SG', 'Jr.', 'Jr.', '6-4', null, null, 12, false, true, false, false),
  ('Davis Dynum', 'Prairie View A&M', 'PF', 'Jr.', 'Jr.', '6-9', null, null, 13, false, true, false, false),
  ('Derrick Rivers', 'Prairie View A&M', 'PG', 'Jr.', 'Jr.', '6-0', null, null, 14, false, true, false, false)
) as v(name, team, position, class_year, yr, height,
  hometown, espn_id, depth_order, starter, is_addition, is_international, is_injured)
where not exists (select 1 from players p where p.name = v.name and p.team = v.team);

-- ── Queens (ASUN, 18 players) ──
insert into teams (name, conference, conf, head_coach, coach)
select 'Queens', 'ASUN', 'ASUN', null, null
where not exists (select 1 from teams where name = 'Queens');
insert into players (name, team, position, class_year, yr, height, hometown,
  espn_id, depth_order, starter, is_addition, is_international, is_injured)
select v.name, v.team, v.position, v.class_year, v.yr, v.height, v.hometown::text,
  v.espn_id::bigint, v.depth_order, v.starter, v.is_addition, v.is_international, v.is_injured from (values
  ('Nasir Mann', 'Queens', 'SG', 'Gr.', 'Gr.', '6-5', 'McNeese', 5176643, 1, true, true, false, false),
  ('Avantae Parker', 'Queens', 'PF', 'Sr.', 'Sr.', '6-9', 'Georgia Southern', 5176801, 2, true, true, false, false),
  ('Dante Kearse', 'Queens', 'SG', 'Jr.', 'Jr.', '6-4', 'The Citadel', 5243245, 3, true, true, false, false),
  ('Corbin Pack', 'Queens', 'SG', 'Sr.', 'Sr.', '6-5', null, null, 4, true, true, false, false),
  ('Reid Celestin', 'Queens', 'SF', 'Sr.', 'Sr.', '6-6', null, null, 5, true, true, false, false),
  ('Matthew Sullivan', 'Queens', 'SG', 'Jr.', 'Jr.', '6-5', null, null, 6, false, true, false, false),
  ('Isaiah Henry', 'Queens', 'SG', 'So.', 'So.', '6-4', null, null, 7, false, true, false, false),
  ('Jack Walter', 'Queens', 'PG', 'So.', 'So.', '6-2', null, null, 8, false, true, false, false),
  ('Jordan Watford', 'Queens', 'SG', 'So.', 'So.', '6-5', null, null, 9, false, true, false, false),
  ('Josh Osayanrhion', 'Queens', 'SF', 'So.', 'So.', '6-8', null, null, 10, false, true, true, false),
  ('Tyler Crider', 'Queens', 'PG', 'So.', 'So.', '6-0', null, null, 11, false, true, false, false),
  ('Atakan Bicer', 'Queens', 'PF', 'Fr.', 'Fr.', '6-10', null, null, 12, false, true, true, false),
  ('Caleb Jones', 'Queens', 'SG', 'Fr.', 'Fr.', '6-4', null, null, 13, false, true, false, false),
  ('Julius Matusek', 'Queens', 'SF', 'Fr.', 'Fr.', '6-7', null, null, 14, false, true, true, false),
  ('Nicholas McLean', 'Queens', 'PF', 'Fr.', 'Fr.', '6-9', null, null, 15, false, true, false, false),
  ('Matthew Walter', 'Queens', 'SG', 'R-So.', 'R-So.', '6-3', null, null, 16, false, true, false, false),
  ('Saif-Allah Zatari', 'Queens', 'SG', 'R-So.', 'R-So.', '6-3', null, null, 17, false, true, true, false),
  ('Seamus Wilson', 'Queens', 'PG', 'R-So.', 'R-So.', '6-0', null, null, 18, false, true, false, false)
) as v(name, team, position, class_year, yr, height,
  hometown, espn_id, depth_order, starter, is_addition, is_international, is_injured)
where not exists (select 1 from players p where p.name = v.name and p.team = v.team);

-- ── Southern Indiana (OVC, 15 players) ──
insert into teams (name, conference, conf, head_coach, coach)
select 'Southern Indiana', 'OVC', 'OVC', null, null
where not exists (select 1 from teams where name = 'Southern Indiana');
insert into players (name, team, position, class_year, yr, height, hometown,
  espn_id, depth_order, starter, is_addition, is_international, is_injured)
select v.name, v.team, v.position, v.class_year, v.yr, v.height, v.hometown::text,
  v.espn_id::bigint, v.depth_order, v.starter, v.is_addition, v.is_international, v.is_injured from (values
  ('Afan Trnka', 'Southern Indiana', 'PG', 'Sr.', 'Sr.', '6-2', 'UT Martin', 5243002, 1, true, true, true, false),
  ('Yuto Yamanouchi-Williams', 'Southern Indiana', 'PF', 'Sr.', 'Sr.', '6-10', 'Oral Roberts', 5108086, 2, true, true, true, false),
  ('Donovan Hunter', 'Southern Indiana', 'SF', 'Sr.', 'Sr.', '6-8', 'Bellarmine', 5176207, 3, true, true, false, false),
  ('LA Hayes', 'Southern Indiana', 'SG', 'Sr.', 'Sr.', '6-6', 'UTEP', 5176206, 4, true, true, false, false),
  ('Fredy-Salam Sylla', 'Southern Indiana', 'SG', 'Jr.', 'Jr.', '6-7', 'Arkansas State', 5312391, 5, true, true, true, false),
  ('Kaden Brown', 'Southern Indiana', 'PG', 'Sr.', 'Sr.', '6-1', 'Wright State', 5177219, 6, false, true, false, false),
  ('Ari Gooch', 'Southern Indiana', 'PG', 'Jr.', 'Jr.', '6-2', 'UAB', 5312078, 7, false, true, false, false),
  ('Didier Maleng', 'Southern Indiana', 'PF', 'Sr.', 'Sr.', '6-9', 'Denver', 5314642, 8, false, true, true, false),
  ('Alem Fejzic', 'Southern Indiana', 'SG', 'Jr.', 'Jr.', '6-3', null, null, 9, false, true, true, false),
  ('Johann Pautsch', 'Southern Indiana', 'PF', 'Jr.', 'Jr.', '6-10', null, null, 10, false, true, true, false),
  ('Josh Smith', 'Southern Indiana', 'PG', 'Jr.', 'Jr.', '6-2', null, null, 11, false, true, false, false),
  ('Josiah Dunham', 'Southern Indiana', 'PG', 'Jr.', 'Jr.', '6-0', null, null, 12, false, true, false, false),
  ('Malachi Knight', 'Southern Indiana', 'SG', 'So.', 'So.', '6-5', null, null, 13, false, true, false, false),
  ('Yesan Warren', 'Southern Indiana', 'PG', 'R-So.', 'R-So.', '6-1', null, null, 14, false, true, false, false),
  ('Maksym Hryshchuk', 'Southern Indiana', 'SF', 'Fr.', 'Fr.', '6-7', null, null, 15, false, true, true, false)
) as v(name, team, position, class_year, yr, height,
  hometown, espn_id, depth_order, starter, is_addition, is_international, is_injured)
where not exists (select 1 from players p where p.name = v.name and p.team = v.team);
