#!/usr/bin/env python3
"""Scrape ESPN team brand colors (1-2 per team, derived from their logos) and
emit ../team-colors.js — a static lookup keyed by normalized team/school name,
used to color team pages and player pages. Re-run to refresh."""
import requests,json,re,os
OUT=os.path.join(os.path.dirname(__file__),"..","team-colors.js")
def norm(s): return re.sub(r'\s+',' ',re.sub(r'[-_]',' ',re.sub(r"[&.'’]",'',(s or '').lower()))).strip()
def nstrip(s): return norm(re.sub(r'\s*\([^)]*\)','',s or ''))
def main():
    r=requests.get("https://site.api.espn.com/apis/site/v2/sports/basketball/mens-college-basketball/teams?limit=900",
                   headers={"User-Agent":"Mozilla/5.0"},timeout=30).json()
    tt=r["sports"][0]["leagues"][0]["teams"]
    teams=[]
    for t in tt:
        tm=t["team"]; logos=tm.get("logos",[])
        c1=tm.get("color"); c2=tm.get("alternateColor")
        teams.append({"display":tm.get("displayName"),"location":tm.get("location"),
            "c1":("#"+c1) if c1 and not c1.startswith("#") else c1,
            "c2":("#"+c2) if c2 and not c2.startswith("#") else c2,
            "logo":logos[0]["href"] if logos else None})
    byloc={norm(t["location"]):t for t in teams if t.get("location")}
    bydisp={norm(t["display"]):t for t in teams}
    find=lambda lbl: byloc.get(norm(lbl)) or bydisp.get(norm(lbl)) or byloc.get(nstrip(lbl)) or bydisp.get(nstrip(lbl))
    M={}
    def put(k,t):
        k=norm(k)
        if k and t and t.get("c1") and k not in M: M[k]={"c1":t["c1"],"c2":t.get("c2"),"logo":t.get("logo")}
    for t in teams:
        put(t.get("display"),t); put(t.get("location"),t)
        if t.get("location"): put(nstrip(t["location"]),t)
    # bbref full-name / abbreviation -> ESPN label aliases
    ALIAS={"louisiana state":"LSU","texas christian":"TCU","brigham young":"BYU","connecticut":"UConn",
     "southern california":"USC","virginia commonwealth":"VCU","southern methodist":"SMU","nevada las vegas":"UNLV",
     "mississippi":"Ole Miss","north carolina state":"NC State","central florida":"UCF","alabama birmingham":"UAB",
     "miami (fl)":"Miami","college of charleston":"Charleston","appalachian state":"App State","san jose state":"San José State",
     "loyola (il)":"Loyola Chicago","loyola (md)":"Loyola Maryland","massachusetts lowell":"UMass Lowell",
     "louisiana monroe":"UL Monroe","maryland baltimore county":"UMBC","illinois chicago":"UIC","nicholls state":"Nicholls",
     "central connecticut state":"Central Connecticut","iu indy":"IU Indianapolis","albany (ny)":"UAlbany",
     "saint francis (pa)":"Saint Francis","fdu":"Fairleigh Dickinson","detroit mercy":"Detroit Mercy",
     "saint marys":"Saint Mary's","mount st marys":"Mount St. Mary's"}
    for full,lbl in ALIAS.items(): put(full,find(lbl))
    js="/* Auto-generated by scrape_team_colors.py — ESPN team brand colors keyed by normalized name. */\n"
    js+="window.TDC_TEAM_COLORS="+json.dumps(M,separators=(',',':'))+";\n"
    js+=("(function(){\n"
      "  function norm(s){return (''+(s||'')).toLowerCase().replace(/[&.'\\u2019]/g,'').replace(/[-_]/g,' ').replace(/\\s+/g,' ').trim();}\n"
      "  function nstrip(s){return norm((''+(s||'')).replace(/\\s*\\([^)]*\\)/g,''));}\n"
      "  window.tdcTeamColor=function(name){var M=window.TDC_TEAM_COLORS;return M[norm(name)]||M[nstrip(name)]||null;};\n"
      "  window.tdcTeamColorHex=function(name){var r=window.tdcTeamColor(name);return r?r.c1:null;};\n"
      "})();\n")
    open(OUT,"w").write(js)
    print(f"wrote team-colors.js — {len(teams)} teams, {len(M)} lookup keys")
if __name__=="__main__": main()
